const GET_ALL_RESTORANTS = "GET_ALL_RESTORANTS";
const GET_FILTERED = "GET_FILTERED";
const GET_AMOUNTPAGES = "GET_AMOUNTPAGES"
const ERROR = "ERROR"
const GET_RESTOURANT_ID = "GET_RESTOURANT_ID"
const GET_ADMIN_USER = "GET_ADMIN_USER"
const POST_USER = "POST_USER"
const GET_USER_EMAIL = "GET_USER_EMAIL"
const LOGIN = "LOGIN"
const LOADING = "LOADING"
const GET_TOKEN = "GET_TOKEN"
const GET_DISH = "GET_DISH"
const ADD_TO_CART = "ADD_TO_CART"
const DELETE_FROM_CART = "DELETE_FROM_CART"
const ADD_FROM_STORE = "ADD_FROM_STORE"
const DELETE_CART = "DELETE_CART"
const FILTER_LANDING = "FILTER_LANDING"
const UPDATE_SUCCESS = "UPDATE_SUCCESS"
const UPDATE_USER = "UPDATE_USER"
const USER_REGISTER = "USER_REGISTER"
const GET_RESERVS = "GET_RESERVS"
const GET_ORDERS = "GET_ORDERS"

module.exports = {
    GET_ALL_RESTORANTS,
    GET_FILTERED,
    GET_AMOUNTPAGES,
    ERROR,
    GET_RESTOURANT_ID,
    GET_ADMIN_USER,
    POST_USER,
    GET_USER_EMAIL,
    LOGIN,
    LOADING,
    GET_TOKEN,
    GET_DISH,
    ADD_TO_CART,
    DELETE_FROM_CART,
    FILTER_LANDING,
    ADD_FROM_STORE,
    DELETE_CART,
    UPDATE_SUCCESS,
    UPDATE_USER,
    USER_REGISTER,
    GET_RESERVS,
    GET_ORDERS,
}
